apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-farm-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-farm
  template:
    metadata:
      labels:
        app: todo-farm
    spec:
      containers:
        - name: todo-farm
          image: todo-farm:local
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-farm-service
spec:
  selector:
    app: todo-farm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
